# jeffgamedev jekyll site 
title: Jeff Brooks - Video Game Developer
email: jeff@jeffgamedev.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal site! I'm Jeff Brooks, a passionate video game developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://www.jeffgamedev.com
twitter_username: jeffgamedev
github_username:  jeffol

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
